default: &default
#  corpid: "corpid"
#  corpsecret: "corpsecret"
#  agentid:  1
# Or if using public account, only need above two line
  appid: "wxb651d8cc809b5118"
  secret: "68974c6e4d347ea80fcf7eb02f7a8339"
  token:    "ZiyoucaishiTestApp0"
  access_token: "/var/tmp/wechat_access_token"
  encrypt_mode: false # if true must fill encoding_aes_key
  encoding_aes_key:  "nliCR726zloyIB7J0XKkQ9KeuiMBSK7wxAbqqnK3BSV"
  jsapi_ticket: "/var/tmp/wechat_jsapi_ticket"

production:
#  corpid:     <%= ENV['WECHAT_CORPID'] %>
#  corpsecret: <%= ENV['WECHAT_CORPSECRET'] %>
#  agentid:    <%= ENV['WECHAT_AGENTID'] %>
# Or if using public account, only need above two line
  appid:      <%= ENV['WECHAT_APPID'] %>
  secret:     <%= ENV['WECHAT_APP_SECRET'] %>
  token:      <%= ENV['WECHAT_TOKEN'] %>
  timeout:    30,
  skip_verify_ssl: true
  access_token:  <%= ENV['WECHAT_ACCESS_TOKEN'] %>
  encrypt_mode: false # if true must fill encoding_aes_key
  encoding_aes_key:  <%= ENV['WECHAT_ENCODING_AES_KEY'] %>
  jsapi_ticket: 

development:
  <<: *default

test:
  <<: *default
